Implement phase 01
Star-Academy/Summer1403-SE-Team04 pull request #4
Opened 2024-07-21 14:28 UTC by mahdizahedii2005

2024-07-21 15:11 UTC, AliSK81 requested changes

2024-07-21 15:11 UTC, AliSK81 commented on StarPhase01/StarPhase01/Program.cs
> +        var  configFilePath = @"..\..\..\database\config.xml";
move file paths to resource (.resx) file

2024-07-21 15:11 UTC, AliSK81 commented on StarPhase01/StarPhase01/Program.cs
> +        catch (Exception e)
catch more specific exception

2024-07-21 15:11 UTC, AliSK81 commented on StarPhase01/StarPhase01/Student.cs
>      public Student(int studentNumber, string firstName, string lastName)
use field initialization

2024-07-21 15:11 UTC, AliSK81 commented on StarPhase01/StarPhase01/Student.cs
> +        return String.Format(CultureInfo.CurrentCulture,"{0} {1} {2:F3} ",FirstName,LastName,GetAverage());
String interpolation using $
https://learn.microsoft.com/en-us/dotnet/csharp/language-reference/tokens/interpolated

2024-07-21 15:11 UTC, AliSK81 commented on StarPhase01/StarPhase01/database/config.xml
وقتی .resx استفاده کنیم دیگه نیازی به این نیست

2024-07-22 05:28 UTC, AliSK81 approved these changes
خسته نباشید

2024-07-22 06:10 UTC, navidnasyry approved these changes

2024-07-22 06:18 UTC, merged