Phase02
Star-Academy/Summer1403-SE-Team04 pull request #5
Opened 2024-07-22 12:07 UTC by SwimmingRieux

2024-07-22 18:13 UTC, navidnasyry requested changes

2024-07-22 18:13 UTC, navidnasyry commented on StarPhase01/StarPhase01/bin/Debug/net8.0/StarPhase01.dll
اینا چیه؟:(((((((((((

2024-07-22 18:13 UTC, navidnasyry commented on StarPhase01/StarPhase01/obj/Debug/net8.0/.NETCoreApp,Version=v8.0.AssemblyAttributes.cs
gitignore pleassssssssssssssssssssssssssssssssse

2024-07-22 18:13 UTC, navidnasyry commented on Phase02/FullTextSearch/database/files/1.txt
whats this?:(((((((((((((

2024-07-22 18:13 UTC, navidnasyry commented on Phase02/FullTextSearch/Reader/DocReader.cs
> +                throw;
write custom exception

2024-07-22 18:13 UTC, navidnasyry commented on Phase02/FullTextSearch/Reader/DocReader.cs
> +                    .Select(s => new Document(s, ReadSingleFile(s, new char[] { ' ', ',', '.', ':', '(', ')', '\n' })))
یه کار بهتر بجای تعریف آرایه اینجا؟

2024-07-22 18:13 UTC, navidnasyry commented on Phase02/FullTextSearch/Model/Document.cs
> +    public Document(string docName, List<string> docWords)
نیازه کانستراکتور؟

2024-07-22 18:13 UTC, navidnasyry commented on Phase02/FullTextSearch/Model/Document.cs
> +    public string DocName { get; set; }
read about init

2024-07-22 18:13 UTC, navidnasyry commented on Phase02/FullTextSearch/Model/InvertedIndex.cs
is it model?

2024-07-22 18:13 UTC, navidnasyry commented on Phase02/FullTextSearch/Logic/MathHelper.cs
> +            throw;
custom exception

2024-07-22 18:13 UTC, navidnasyry commented on Phase02/FullTextSearch/Logic/MathHelper.cs
> +    public static List<T> Union<T>( this List<List<T>> list)
چرا نیاز به اکتنشن متد دارید؟

2024-07-22 18:13 UTC, navidnasyry commented on Phase02/FullTextSearch/Logic/MathHelper.cs
> +    public static List<T> Union<T>( this List<List<T>> list)
https://www.tutorialspoint.com/chash-program-to-find-union-of-two-or-more-lists

2024-07-22 18:13 UTC, navidnasyry commented on Phase02/FullTextSearch/Logic/MathHelper.cs
> +    public static List<T> Intersect<T>(this List<List<T>> list)
آمادش نیست؟

2024-07-22 18:13 UTC, navidnasyry commented on Phase02/FullTextSearch/Logic/WordFormatFixer.cs
کلا یه مرحله preprocess داریم برای داده ها و کلمه ورودی که بهتره مشخص باشه کجا دارین پیش‌پردازش هارو رو انجام میدین

2024-07-22 18:13 UTC, navidnasyry commented on Phase02/FullTextSearch/Logic/WordFormatFixer.cs
> +    private static EnglishPorter2Stemmer stemmer = new EnglishPorter2Stemmer();
read about naming convention in dotnet

2024-07-22 18:13 UTC, navidnasyry commented on Phase02/FullTextSearch/Logic/WordSearcher.cs
> +        var mustExist = (from word in words
اممممممممممم....من باید بفهمم این یه خط کدرو اره؟:)))

2024-07-22 18:13 UTC, navidnasyry commented on Phase02/FullTextSearch/Logic/WordSearcher.cs
> +        var mustExist = (from word in words
دیباگش سخته

2024-07-22 18:13 UTC, navidnasyry commented on Phase02/FullTextSearch/Logic/WordSearcher.cs
> +        var mustExist = (from word in words
فهمش سخته در نگاه اول

2024-07-22 18:13 UTC, navidnasyry commented on Phase02/FullTextSearch/Logic/WordSearcher.cs
> +            throw;
custom exception

2024-07-22 18:13 UTC, navidnasyry commented on Phase02/FullTextSearch/Logic/WordSearcher.cs
> +        var mustExist = (from word in words
و کلا خیلی کار ها داره انجام میشه اینجا

2024-07-23 07:29 UTC, SwimmingRieux commented on Phase02/FullTextSearch/Logic/WordFormatFixer.cs
متوجه نشدم!؟

2024-07-23 07:42 UTC, SwimmingRieux commented on Phase02/FullTextSearch/Model/Document.cs
> +    public Document(string docName, List<string> docWords)
چرا نیاز نیست؟ استفاده هم که شده.

2024-07-23 11:41 UTC, AliSK81 requested changes
فاز 1 توی این PR چیکار میکنه؟

2024-07-23 12:19 UTC, SwimmingRieux commented
> فاز 1 توی این PR چیکار میکنه؟

حذف کردیمش. الان delete شدن.

2024-07-23 12:25 UTC, AliSK81 requested changes

2024-07-23 12:25 UTC, AliSK81 commented on Phase02/FullTextSearch/DataStructure/InvertedIndex.cs
> +    }
linq (ToDictionary)

2024-07-23 12:25 UTC, AliSK81 commented on Phase02/FullTextSearch/Logic/EmptyRemover.cs
> +            select word).ToList();
LINQ to Objects instead of SQL
https://xerostory.com/8-types-of-linq-query-in-csharp/

2024-07-23 12:25 UTC, AliSK81 commented on Phase02/FullTextSearch/Logic/MathHelper.cs
> +            var list1 = new List<T>();
list1?

2024-07-23 12:25 UTC, AliSK81 commented on Phase02/FullTextSearch/Logic/WordSearcher.cs
?

2024-07-23 12:25 UTC, AliSK81 commented on Phase02/FullTextSearch/Program.cs
> +                    .ToList().RemoveEmptyCells())).ToList();
long line
بشکنیم به چند خط

2024-07-23 13:59 UTC, merged