Phase03
Star-Academy/Summer1403-SE-Team04 pull request #6
Opened 2024-07-24 13:32 UTC by mahdizahedii2005

2024-07-26 15:13 UTC, mahdizahedii2005 commented on Phase03/FullTextSearch/Control/Logic/WordSearcher.cs
تصمیمی که گرفتیم اینه که فردا این کلاس را منطقش را کلا تغیر دهیم برای همین کلا این فایل را به نظرم ignore کنید

2024-07-26 20:51 UTC, navidnasyry requested changes

2024-07-26 20:51 UTC, navidnasyry commented on Phase03/FullTextSearch/Control/Controller.cs
> +public class Controller
bad name

2024-07-26 20:51 UTC, navidnasyry commented on Phase03/FullTextSearch/Control/Logic/WordSearcher.cs
در نظر بگیرین کلا هیچ کلاسی نباید وابسته به کلاس دیگه ای باشه:)

2024-07-26 20:51 UTC, navidnasyry commented on Phase03/FullTextSearch/Control/Logic/WordSearcher.cs
و single responsibility فراموش نشه

2024-07-26 20:51 UTC, navidnasyry commented on Phase03/FullTextSearch/Control/OutputHandler.cs
> +public class OutputHandler
read about Dependency inversion

2024-07-26 20:51 UTC, navidnasyry commented on Phase03/.gitignore
کلا پوشه بندی مرتب تر بشه

2024-07-26 20:51 UTC, navidnasyry commented on Phase03/.gitignore
سعی کنین بجای abstract کلاس ها رو سینگلتون کنین

2024-07-27 06:18 UTC, SwimmingRieux commented on Phase03/FullTextSearch/Model/Document.cs
> +    public IEnumerator<string> GetEnumerator()
این حرکت منطقیه یا اینکه روی خود doc.docWords ایتریت کنیم؟

2024-07-27 06:48 UTC, SwimmingRieux commented on Phase03/FullTextSearch/Model/DataStructure/InvertedIndex.cs
> +    public static List<InvertedIndex> InvertedIndicesList { get; }=new List<InvertedIndex>();
اینطوری بهتره یا اینکه یه کلاس keeper سینگلتون بسازیم و هر سری توی اون ادد کنیم؟

2024-07-27 11:32 UTC, mahdijafariii commented on Phase03/FullTextSearch/Control/Initializer.cs
> +        directoryList.ForEach(path => InvertedIndexBuilder.InvertedIndexBuilderInstance.BuildInvertedIndex(path));
بهتره که این کلاس سینگلتون نباشه ، کلاس سینگلتون کارش خیلی باید ساده باشه و invertedindex مناسب کلاس سینگلتون نیست
البته که فاز بعدی که باید تست بنویسیم هم نمیتونید براش تست بنویسید و باید عوضش کنید

2024-07-27 11:34 UTC, mahdijafariii commented on Phase03/FullTextSearch/Control/Logic/InvertedIndexBuilder.cs
> +    {
بهتره که این کلاس سینگلتون نباشه ، کلاس سینگلتون کارش خیلی باید ساده باشه و invertedindex مناسب کلاس سینگلتون نیست
البته که فاز بعدی که باید تست بنویسیم هم نمیتونید براش تست بنویسید و باید عوضش کنید

2024-07-27 11:35 UTC, mahdijafariii commented on Phase03/FullTextSearch/Control/Logic/DocumentsLoader/DocumentLoader.cs
> +    {
دیفالت داره خود C#

2024-07-27 11:35 UTC, mahdijafariii commented on Phase03/FullTextSearch/Control/Logic/DocumentsLoader/DocumentLoader.cs
> +
بازم سینگلتون

2024-07-27 11:40 UTC, mahdijafariii commented on Phase03/FullTextSearch/Control/Logic/DocumentsLoader/WordsListFormatFixer.cs
> +}
بجای استفاده از استاتیک میتونید یه واسط بزنید که کلاس هایی مثل small word , extra space , و... بیان ایمپلمنت کنن و اون تابع اجرا کنن ( یچیزی تو مایه ها design factory )  ولی نصفش

2024-07-27 11:48 UTC, mahdijafariii commented on Phase03/FullTextSearch/Control/Logic/WordRootProcessor.cs
> +
خیلی جالب بود ایول :)

2024-07-27 11:50 UTC, mahdijafariii commented on Phase03/FullTextSearch/Control/Reader/FileProcessingException.cs
> +}
read about custom exception

2024-07-27 11:52 UTC, mahdijafariii commented on Phase03/FullTextSearch/Control/Reader/FileReader.cs
> +            return characters as char[] ?? characters.ToArray();
use Regex

2024-07-27 11:53 UTC, mahdijafariii commented on Phase03/FullTextSearch/Control/search/DocFinder.cs
> +    private DocFinder(){}
default c#

2024-07-27 12:02 UTC, mahdijafariii commented on Phase03/FullTextSearch/Control/search/SearchStrategy/TargetedStrategy.cs
> +    }
single responsibility for your methods

2024-07-27 12:03 UTC, mahdijafariii commented on Phase03/FullTextSearch/Control/search/SearchStrategy/TargetedStrategy.cs
> +    }
میتونی اول اونایی که همشون هست با اونی که باید حداقل یکی باشه را اشتراک بگیری و بعد یه اکسپ بزنی منهای mustNot کنی

2024-07-27 12:11 UTC, mahdijafariii commented on Phase03/FullTextSearch/Control/search/StrategySet/FindSetsByName.cs
> +}
توی پروژه قبلی در مورد استفاده آرایه جای لیست خوندیم 
جالبه بدونید دسترسی به عناصر لیست اینجا O(1)
اضافه کردن به لیست هم در بهترین حالت و میانگین o(1) 
ولی آرایه o(n) و البته خیلی موارد دیگ که باعث میشه لیست توی سی شارپ خیلی ارجحیت داشته باشه

2024-07-27 12:53 UTC, AliSK81 requested changes
لطفا این موارد دقت بشه:
1. سینگلتون استفاده نکنید (چرا؟)
2. تمام فایل ها ریفرمت بشه
3. تمام منطق ها اینترفیس داشته باشن (چرا؟)
4. کامنت های گذاشته شده رو تعمیم بدید به کل کد (برای تکرار همه جا کامنت گذاشته نشده)

2024-07-27 12:53 UTC, AliSK81 commented on Phase03/FullTextSearch/Program.cs
> +       Initializer.InitializerInstance.Init(new List<string>(){Resources.documentsPath},
https://stackoverflow.com/questions/896342/resource-resx-file-key-naming-conventions

2024-07-27 12:53 UTC, AliSK81 commented on Phase03/FullTextSearch/Control/Initializer.cs
> +public class Initializer
add private constructor

2024-07-27 12:53 UTC, AliSK81 commented on Phase03/FullTextSearch/Control/Logic/DocumentsLoader/DocumentLoader.cs
> +        return documents.EditWords();
single responsibility

2024-07-27 12:53 UTC, AliSK81 commented on Phase03/FullTextSearch/Control/Logic/DocumentsLoader/DocumentLoader.cs
> +public class DocumentLoader
چرا اینترفیس نداره؟
چرا باید داشته باشه؟

2024-07-27 12:53 UTC, AliSK81 commented on Phase03/FullTextSearch/Control/Logic/DocumentsLoader/DocumentWordsEditor.cs
> +public static class DocumentWordsEditor
interface

2024-07-27 12:53 UTC, AliSK81 commented on Phase03/FullTextSearch/Control/Logic/DocumentsLoader/WordsListFormatFixer.cs
> +public static class WordsListFormatFixer
interface

2024-07-27 12:53 UTC, AliSK81 commented on Phase03/FullTextSearch/Control/Logic/DocumentsLoader/WordsListFormatFixer.cs
> +    public static IEnumerable<string> FixWordsList(this IEnumerable<string> documentWords)
فیکس یعنی چی؟ باید از اسم کلاس و توابع دقیقا مشخص باشه چه اتفاقی میفته

2024-07-27 12:53 UTC, AliSK81 commented on Phase03/FullTextSearch/Control/Logic/DocumentsLoader/WordsListFormatFixer.cs
> +            .RemoveSmallWords().ToList();
single responsibility

2024-07-27 12:53 UTC, AliSK81 commented on Phase03/FullTextSearch/Control/Logic/InvertedIndexBuilder.cs
> +public class InvertedIndexBuilder
این کلاس بیشتر شبیه creator هست تا builder
اینترفیس هم نداره

2024-07-27 12:53 UTC, AliSK81 commented on Phase03/FullTextSearch/Control/Logic/MathHelper.cs
> +            Console.WriteLine(e);
برای خروجی اینترفیس نداشتین؟

2024-07-27 12:53 UTC, AliSK81 commented on Phase03/FullTextSearch/Control/Logic/MathHelper.cs
> +            return !enumberList.Any() ? new List<T>() : enumberList.Aggregate((current, next) => current.Union(next).ToList());
کد خوانا نیست

2024-07-27 12:53 UTC, AliSK81 commented on Phase03/FullTextSearch/Control/Logic/SmallWordsRemover.cs
> +public static class SmallWordsRemover
interface

2024-07-27 12:53 UTC, AliSK81 commented on Phase03/FullTextSearch/Control/Logic/SmallWordsRemover.cs
> +    public static IEnumerable<string> RemoveSmallWords(this IEnumerable<string> list)
الان شما برای این تایپ اکستنشن متد نوشتین
تو کل پروژه هر لیستی از استرینگ این تابع رو براش پیشنهاد میده
منطقیه؟

2024-07-27 12:53 UTC, AliSK81 commented on Phase03/FullTextSearch/Control/Logic/SmallWordsRemover.cs
> +    private static readonly IEnumerable<String> SmallWordsList = FileReader.FileReaderInstance.Read(Resources.smallWordsPath);
hashset

2024-07-27 12:53 UTC, AliSK81 commented on Phase03/FullTextSearch/Control/Logic/WordFormatFixer.cs
> +}
اینجا هم اکستنشن متد خوب نیست

2024-07-27 12:53 UTC, AliSK81 commented on Phase03/FullTextSearch/Control/Reader/FileReader.cs
> +public class FileReader : IFileReader
چه فایلی؟

2024-07-27 12:53 UTC, AliSK81 commented on Phase03/FullTextSearch/Control/Reader/FileReader.cs
> +      }
اصلا خوانا نیست

2024-07-27 12:53 UTC, AliSK81 commented on Phase03/FullTextSearch/Control/Reader/FileReader.cs
> +      }
میتونه منطق جدا بشه

2024-07-27 12:53 UTC, AliSK81 commented on Phase03/FullTextSearch/Control/search/SearchStrategy/StrategyNotFoundException.cs
> +    public StrategyNotFoundException() : base("strategy not found pleas check your name")
move messages to resource file

2024-07-27 12:53 UTC, AliSK81 commented on Phase03/FullTextSearch/Control/search/SearchStrategy/TargetedStrategy.cs
> +            AtLeastOneExistSet.Instance);
پاس دادن static property چه نکته ای داره؟ بدون پاس دادن هم میتونیم دسترسی داشته باشیم.

2024-07-27 12:53 UTC, AliSK81 commented on Phase03/FullTextSearch/Control/search/SearchStrategy/TargetedStrategy.cs
> +            var atLeastOneExists = strategySets.FindByName("AtLeastOneExists").GetValidDocs(words, index);
اگه رشته ها اشتباه تایپی داشته باشه و .. چی میشه؟ چیکار میتونیم بکنیم؟
این منطق فکتوری نیست؟

2024-07-27 12:53 UTC, AliSK81 commented on Phase03/FullTextSearch/Control/search/StrategySet/AtLeastOneExistSet.cs
> +            .Union();
long line

2024-07-27 12:53 UTC, AliSK81 commented on Phase03/FullTextSearch/Control/search/StrategySet/AtLeastOneExistSet.cs
> +        return "AtLeastOneExists";
use const property or enum

2024-07-27 12:53 UTC, AliSK81 commented on Phase03/FullTextSearch/Model/DataStructure/InvertedIndex.cs
> +    public override string ToString()
چه نیازیه؟

2024-07-27 12:53 UTC, AliSK81 commented on Phase03/FullTextSearch/Model/DataStructure/InvertedIndex.cs
> +    public static List<InvertedIndex> InvertedIndicesList { get; }=new List<InvertedIndex>();
هیچکدوم

2024-07-27 12:53 UTC, AliSK81 commented on Phase03/FullTextSearch/Model/DataStructure/InvertedIndex.cs
> +    public static List<InvertedIndex> InvertedIndicesList { get; }=new List<InvertedIndex>();
این لیست استاتیک باید حذف بشه اصلا خوب نیست (چرا؟)

2024-07-27 13:05 UTC, mahdizahedii2005 commented on Phase03/FullTextSearch/Model/DataStructure/InvertedIndex.cs
> +    public override string ToString()
debug

2024-07-28 07:47 UTC, mahdizahedii2005 commented on Phase03/FullTextSearch/Control/search/SearchStrategy/TargetedStrategy.cs
> +            AtLeastOneExistSet.Instance);
فقط این استراتژی خاتص به این ها نیاز داریم ممکنه یک استراتژی دیگه با یک سری proprty دیگه نیاز باشه

2024-07-28 08:13 UTC, msmahdinejad commented on Phase03/FullTextSearch/Controllers/Logic/MathHelper.cs
> +            Console.WriteLine(e);
ظاهرا چاپ در تابع مشکل داره

2024-07-28 08:13 UTC, msmahdinejad commented on Phase03/FullTextSearch/Controllers/Reader/FileReader.cs
> +            var characters = new Regex(@"[0-9:;A-Z\[\\\]a-z]").ToString().ToCharArray();
Regex in fileReader != Single Responsibility

2024-07-28 08:13 UTC, msmahdinejad commented on Phase03/FullTextSearch/Model/DataStructure/InvertedIndex.cs
> +    public Dictionary<string, IEnumerable<string>> InvertedIndexMap { get; init; }
not open/close
چون فقط بین کلمات میشه سرچ زد

2024-07-28 08:13 UTC, msmahdinejad commented on Phase03/FullTextSearch/Model/Document.cs
> +public class Document(string docName, IEnumerable<string> docWords) : IEnumerable<string>
اینترفیس برای دیتا های متفاوت نیاز نیست؟!
اگر کلاسی غیر از داکیومنت داشتیم

2024-07-28 08:13 UTC, msmahdinejad commented on Phase03/FullTextSearch/Model/DataStructure/InvertedIndex.cs
> +    private Dictionary<string, IEnumerable<string>>  BuildInvertedIndex(IEnumerable<Document> documents)
Single Responsibility !!

2024-07-28 12:41 UTC, mahdizahedii2005 reviewed
ما تقریبا در همه متد ها داریم از اینترفیس استفاده میکنیم 
ولی به دلیل اینکه خارج از کلاس چند شی بدون استفاده ساخته نشود 
رفرنس های اولیه توابع را سینگلتون ان کلاس را به ان فرستادیم.

2024-07-28 15:26 UTC, navidnasyry approved these changes

2024-07-28 15:26 UTC, navidnasyry commented on Phase03/FullTextSearch/Controllers/Reader/Abstraction/ITxtReader.cs
> +    IEnumerable<string> Read(string path);
اون IEnumerable هایی که می‌دونین خروجیش تغییر نباید بکنه رو تغییر بدین به IReadOnlyList

2024-07-28 15:26 UTC, navidnasyry commented on Phase03/FullTextSearch/Controllers/Reader/TxtReader.cs
> +    private readonly string _splitPattern = @"[^a-zA-Z1-9]";
get from const class

2024-07-28 15:26 UTC, navidnasyry commented on Phase03/FullTextSearch/Controllers/Reader/Abstraction/IDocReader.cs
> +    public IEnumerable<string> Read(string path, IGarbageRemover remover);
remove public

2024-07-28 15:26 UTC, navidnasyry commented on Phase03/FullTextSearch/Controllers/Reader/Abstraction/IDocReader.cs
> +    public IEnumerable<string> Read(string path, IGarbageRemover remover);
in all interfaces

2024-07-28 15:26 UTC, navidnasyry commented on Phase03/FullTextSearch/Controllers/Reader/Abstraction/IDocReader.cs
> +    public IEnumerable<string> Read(string path, IGarbageRemover remover);
why?

2024-07-29 06:28 UTC, AliSK81 requested changes
چندتا نکته مهم هست که رعایت بشه
1.نامگذاری ها دقیق باشه و باید ازش متوجه بشیم هر اینترفیس و تابع چه کاری میکنه
مثلا Initializer مشخص نیست چیو init میکنه. 
2. سینگلتون استفاده نکنیم
3. اکسپشن های کاستوم اگه نیاز شد تعریف و هندل کنیم و بقیه اکسپشن هارو نیاز نیست هندل کنیم (کار درستی هم نیست)
4. لطفا کامنت هارو به کل کد تعمیم بدید و اشکالات مشابه رو حل کنید

2024-07-29 06:28 UTC, AliSK81 commented on Phase03/FullTextSearch/Assets/inverted_index.json
فایل خالی؟

2024-07-29 06:28 UTC, AliSK81 commented on Phase03/FullTextSearch/Controllers/Abstraction/IInitializer.cs
> +public interface IInitializer
بهتر بود اسم دقیق تری میزاشتیم
مثلا ServiceStartupInitializer

2024-07-29 06:28 UTC, AliSK81 commented on Phase03/FullTextSearch/Controllers/Logic/Abstraction/IDocBuilder.cs
> +    Document Builed(string docPath, IDocReader docReader);
typo: Build

2024-07-29 06:28 UTC, AliSK81 commented on Phase03/FullTextSearch/Controllers/Logic/Abstraction/IDocBuilder.cs
> +    Document Builed(string docPath, IDocReader docReader);
inject IDocReader  through constructor

2024-07-29 06:28 UTC, AliSK81 commented on Phase03/FullTextSearch/Controllers/Logic/Abstraction/IDocumentLoader.cs
> +        List<IStringReformater> reformaters, IDocBuilder builder);
constructor injection is preferred

2024-07-29 06:28 UTC, AliSK81 commented on Phase03/FullTextSearch/Controllers/Logic/Abstraction/IGarbageRemover.cs
> +    IEnumerable<string> Remove(IEnumerable<string> list);
list of what? choose better name

2024-07-29 06:28 UTC, AliSK81 commented on Phase03/FullTextSearch/Controllers/Logic/Abstraction/IInvertedIndexCreator.cs
> +    void CreateInvertedIndex(string directoryPath, IInvertedIndexWriter writer, IDocumentLoader documentLoader);
constructor injection

2024-07-29 06:28 UTC, AliSK81 commented on Phase03/FullTextSearch/Controllers/Logic/DocumentsLoader/WordsListFormatFixer.cs
> +        });
do not modify input arguments (why?)
create a new list of fiexed words and return

2024-07-29 06:28 UTC, AliSK81 commented on Phase03/FullTextSearch/Controllers/Logic/InvertedIndexLoader.cs
> +        };
define static readonly property
private static readonly JsonSerializerOptions

2024-07-29 06:28 UTC, AliSK81 commented on Phase03/FullTextSearch/Controllers/Logic/InvertedIndexWriter.cs
> +        };
make option a static propety

2024-07-29 06:28 UTC, AliSK81 commented on Phase03/FullTextSearch/Controllers/Logic/MathHelper.cs
> +        }
never catch system exceptions
you can define custom exception and handle it if you want

2024-07-29 06:28 UTC, AliSK81 commented on Phase03/FullTextSearch/Controllers/Logic/SmallWordsRemover.cs
> +        TxtReader.TxtReaderInstance.Read(Resources.SmallWordsPath).ToHashSet();
استاتیک خوبه واسه وقتی یه استرینگ ساده یا آپشن ثابتی تعریف میکنیم
اینجا خوب نیست استاتیک تعریف کردیم
پیشنهادم اینه ریفکتور بشه

2024-07-29 06:28 UTC, AliSK81 commented on Phase03/FullTextSearch/Controllers/OutputHandler.cs
> +            OutputRendererKeeper.Instance.OutputRenderer.Render("Nothing was found for your word");
move messages to .resx file

2024-07-29 06:28 UTC, AliSK81 commented on Phase03/FullTextSearch/Controllers/QueryReceiver.cs
> +        QuerySearcher.Instance.ProcessQuery(query, loader);
dependency inversion violated

2024-07-29 06:28 UTC, AliSK81 commented on Phase03/FullTextSearch/Controllers/Reader/Abstraction/IDocReader.cs
> +    IEnumerable<string> Read(string path, IGarbageRemover remover);
چرا doc reader وظیفه remove کردن هم داره؟ 
single responsibility violated

2024-07-29 06:28 UTC, AliSK81 commented on Phase03/FullTextSearch/Controllers/Reader/DocReader.cs
> +        return remover.Remove(TxtReader.TxtReaderInstance.Read(path));
DIP violated

2024-07-29 06:28 UTC, AliSK81 commented on Phase03/FullTextSearch/Controllers/search/SearchStrategy/TargetedStrategy.cs
> +        var atLeastOneExists = strategySets.FindByName(StrategySetEnum.AtLeastOneExist).GetValidDocs(words, index);
refactor with Factory design pattern

2024-07-29 06:28 UTC, AliSK81 commented on Phase03/FullTextSearch/Controllers/search/StrategySet/AtLeastOneExistSet.cs
> +    public static AtLeastOneExistSet Instance => _atLeastOneExistSet ??= new AtLeastOneExistSet();
DIP

2024-07-29 06:28 UTC, AliSK81 commented on Phase03/FullTextSearch/Controllers/search/StrategySet/FindSetsByName.cs
> +    public static IStrategySet? FindByName(this IStrategySet[] sets, StrategySetEnum name)
اینجا بهتره اسم sets رو بزاریم strategies 
نامگذاری ها در کل میتونه بهتر بشه

2024-07-29 06:28 UTC, AliSK81 commented on Phase03/FullTextSearch/View/Cli/CliInputListener.cs
> +            "Enter your word (if you want to finish the program enter 'exit') : ");
to .resx

2024-07-29 06:28 UTC, AliSK81 commented on Phase03/FullTextSearch/View/Cli/CliInputListener.cs
> +        while (query != "exit")
private const string

2024-07-29 12:32 UTC, AliSK81 approved these changes

2024-07-29 12:55 UTC, merged