Phase04
Star-Academy/Summer1403-SE-Team04 pull request #8
Opened 2024-07-30 15:22 UTC by mahdizahedii2005

2024-07-31 06:22 UTC, navidnasyry requested changes

2024-07-31 06:22 UTC, navidnasyry commented on .gitignore
کد‌های فاز چهار کو پس؟ فاز چهار باید شامل کد و تست باشه

2024-07-31 06:22 UTC, navidnasyry commented on Phase04/Phase4Solution/FullTextSearchTest/Controllers/Logic/DocBuilderTest.cs
> +}
//Arrange
//Act
//Assert
https://medium.com/@rojasjimenezjosea/aaa-unit-testing-688e3e61902a
https://www.linkedin.com/pulse/elevate-your-unit-testing-aaa-pattern-c-collins-tonui/

2024-07-31 06:22 UTC, navidnasyry commented on Phase04/Phase4Solution/FullTextSearchTest/Controllers/Logic/DocumentsLoader/DocumentLoaderTest.cs
> +    }
AAA

2024-07-31 06:22 UTC, navidnasyry commented on Phase04/Phase4Solution/FullTextSearchTest/Controllers/Logic/DocumentsLoader/DocumentLoaderTest.cs
> +    }
read about Red Green Refactor
https://www.codecademy.com/article/tdd-red-green-refactor

2024-07-31 06:22 UTC, navidnasyry commented on Phase04/Phase4Solution/FullTextSearchTest/Controllers/Logic/DocumentsLoader/DocumentWordsEditorTest.cs
> +        testq.Remove(Arg.Any<IEnumerable<string>>()).Returns(new[] { "a" });
testq?

2024-07-31 06:22 UTC, navidnasyry commented on Phase04/Phase4Solution/FullTextSearchTest/Controllers/Logic/DocumentsLoader/DocumentWordsEditorTest.cs
> +    private IStringReformater test;
test?:)

2024-07-31 06:22 UTC, navidnasyry commented on Phase04/Phase4Solution/FullTextSearchTest/Controllers/Logic/SmallWordsRemoverTest.cs
> +    }
بهتر نیست در این حالت‌ها اکسپشن بدیم؟

2024-07-31 06:22 UTC, navidnasyry commented on Phase04/Phase4Solution/FullTextSearchTest/Controllers/Reader/TxtReaderTest.cs
> +    }
آدرس ولید؟ وابسته به سیستمی و آدرس کدی میشه که داره اجرا میشه؟

2024-07-31 06:22 UTC, navidnasyry commented on Phase04/Phase4Solution/FullTextSearchTest/Controllers/Reader/TxtReaderTest.cs
> +    }
آدرس ابسولوت؟

2024-07-31 06:22 UTC, navidnasyry commented on Phase04/Phase4Solution/FullTextSearchTest/Controllers/search/DocFinderTest.cs
> +        if (string.IsNullOrEmpty(query) || !_index.InvertedIndexMap.ContainsKey(query))
این دو تا تست میشه

2024-07-31 06:22 UTC, navidnasyry commented on Phase04/Phase4Solution/FullTextSearchTest/Controllers/search/DocFinderTest.cs
> +    public void Find_ShouldReturnExpectedResults(string query)
اسم با همون کانونشن که گفتم

2024-07-31 06:22 UTC, navidnasyry commented on Phase04/Phase4Solution/FullTextSearchTest/Controllers/search/DocFinderTest.cs
> +        {
تا جایی که میتونیم تست‌های ریز باید بنویسیم
read about **unit** test

2024-07-31 06:22 UTC, navidnasyry commented on Phase04/Phase4Solution/FullTextSearchTest/Controllers/search/SearchStrategy/TargetedStrategyTest.cs
> +    [InlineData("love")]
اینا میتونن fact باشن

2024-07-31 06:33 UTC, navidnasyry requested changes
read about equal method for class

2024-07-31 15:40 UTC, navidnasyry requested changes

2024-07-31 15:40 UTC, navidnasyry commented on Phase04/Phase4Solution/FullTextSearchTest/Controllers/Logic/DocBuilderTest.cs
> +        Assert.Null(_docBuilder.Build(path));
جدا بشه بخش های AAA

2024-07-31 15:40 UTC, navidnasyry commented on Phase04/Phase4Solution/FullTextSearchTest/Controllers/Logic/DocBuilderTest.cs
> +    public void Build_ShouldBeNull_IfPathIsNullOrEmpty(string path)
ShouldReturnNull

2024-07-31 15:40 UTC, navidnasyry commented on Phase04/Phase4Solution/FullTextSearchTest/Controllers/Logic/DocBuilderTest.cs
> +        _txtReader.Read(Arg.Any<string>()).Returns(new []{"ali"});
چرا ورودی Read رو دقیق‌تر ندیم؟

2024-07-31 15:40 UTC, navidnasyry commented on Phase04/Phase4Solution/FullTextSearchTest/Controllers/Logic/DocBuilderTest.cs
> +        var check = _docBuilder.Build("mamad");
var actual

2024-07-31 15:40 UTC, navidnasyry commented on Phase04/Phase4Solution/FullTextSearchTest/Controllers/Logic/DocBuilderTest.cs
> +        var result = new Document("mamad", new[] { "ali" });
var expected

2024-07-31 15:40 UTC, navidnasyry commented on Phase04/Phase4Solution/FullTextSearchTest/Controllers/Logic/DocBuilderTest.cs
> +        Assert.Equal(check,result);
?پارامتر اول باید expected  باشه یا actual

2024-07-31 15:40 UTC, navidnasyry commented on Phase04/Phase4Solution/FullTextSearchTest/Controllers/Logic/DocumentsLoader/DocumentLoaderTest.cs
> +        Assert.Equal(result,check);
برای Assert  کردن دو تا لیست همیشه از Equal میتونیم استفاده کنیم؟

2024-07-31 15:40 UTC, navidnasyry commented on Phase04/Phase4Solution/FullTextSearchTest/Controllers/Logic/DocumentsLoader/DocumentLoaderTest.cs
> +    public void LoadDocumentsList_ShouldBeLoadedDoc_IfPathIsNormal()
نامگذاری تابع تست و  Actual , Expected بهتر بشه

2024-07-31 15:40 UTC, navidnasyry commented on Phase04/Phase4Solution/FullTextSearchTest/Controllers/Logic/DocumentsLoader/DocumentWordsEditorTest.cs
> +    public void EditWords_ShouldBeEdited_IfPathIsNormal()
بخش Should دقیق تر بشه

2024-07-31 15:40 UTC, navidnasyry commented on Phase04/Phase4Solution/FullTextSearchTest/Controllers/Logic/DocumentsLoader/DocumentWordsEditorTest.cs
> +        //arrange
// Arrange
// Act
// Assert

2024-07-31 15:40 UTC, navidnasyry commented on Phase04/Phase4Solution/FullTextSearchTest/Controllers/Logic/MathHelperTest.cs
> +
AAA

2024-07-31 15:40 UTC, navidnasyry commented on Phase04/Phase4Solution/FullTextSearchTest/Controllers/Logic/MathHelperTest.cs
> +    }
AAAAAAAAAAAAAAAAAAA

2024-07-31 15:40 UTC, navidnasyry commented on Phase04/Phase4Solution/FullTextSearchTest/Controllers/Logic/SmallWordsRemoverTest.cs
> +    }
AAA

2024-07-31 15:40 UTC, navidnasyry commented on Phase04/Phase4Solution/FullTextSearchTest/Controllers/Logic/SmallWordsRemoverTest.cs
> +        var check = new[] { "ali", "mamad", "is" };
expected

2024-07-31 15:40 UTC, navidnasyry commented on Phase04/Phase4Solution/FullTextSearchTest/Controllers/Logic/SmallWordsRemoverTest.cs
> +        Assert.Equal(check,result);
prettier

2024-07-31 15:40 UTC, navidnasyry commented on Phase04/Phase4Solution/FullTextSearchTest/Controllers/Logic/StringProcessor/QueryHandlerTest.cs
> +        //assert
prettier
تمام بخش‌های AAA کامل نوشته بشه

2024-07-31 15:40 UTC, navidnasyry commented on Phase04/Phase4Solution/FullTextSearchTest/Controllers/Logic/StringProcessor/QueryHandlerTest.cs
> +        //assert
:))

2024-07-31 15:40 UTC, navidnasyry commented on Phase04/Phase4Solution/FullTextSearchTest/Controllers/Logic/StringProcessor/QueryHandlerTest.cs
> +
reformat

2024-07-31 15:40 UTC, navidnasyry commented on Phase04/Phase4Solution/FullTextSearchTest/Controllers/Logic/StringProcessor/QueryHandlerTest.cs
> +        //assert
همه‌ی تست‌ها رعایت شود لطفا

2024-07-31 15:40 UTC, navidnasyry commented on Phase04/Phase4Solution/FullTextSearchTest/Controllers/Logic/StringProcessor/QueryHandlerTest.cs
> +        for (var i = 0; i < outPut.Length; i++) outPut[i] = result[i + 1];
word.SplitIntoFormattedWords(list)
این act نیست؟

2024-07-31 15:40 UTC, navidnasyry commented on Phase04/Phase4Solution/FullTextSearchTest/Controllers/Logic/StringProcessor/QueryHandlerTest.cs
> +        params string[] result)
ایضا...کامنت قبلی

2024-07-31 15:40 UTC, navidnasyry commented on Phase04/Phase4Solution/FullTextSearchTest/Controllers/Logic/StringProcessor/ToLowerTest.cs
> +
کامل جداسازی بشه بخش‌های مختلف برای AAA

2024-07-31 15:40 UTC, navidnasyry commented on Phase04/Phase4Solution/FullTextSearchTest/Controllers/Logic/StringProcessor/ToLowerTest.cs
> +    }
اقاااااااااااااااا
_toLower.FixWordFormat(word)
باور کنین Act عههههههههه

2024-07-31 15:40 UTC, navidnasyry commented on Phase04/Phase4Solution/FullTextSearchTest/Controllers/Logic/StringProcessor/ToRootTest.cs
> +
:(

2024-07-31 15:40 UTC, navidnasyry commented on Phase04/Phase4Solution/FullTextSearchTest/Controllers/Logic/StringProcessor/ToRootTest.cs
> +    }
:(

2024-07-31 15:40 UTC, navidnasyry commented on Phase04/Phase4Solution/FullTextSearchTest/Controllers/Reader/TxtReaderTest.cs
> +    }
reformat

2024-07-31 15:40 UTC, navidnasyry commented on Phase04/Phase4Solution/FullTextSearchTest/Controllers/search/SearchStrategy/TargetedStrategyTest.cs
> +        Assert.NotEmpty(result);
Assert دقیق تر

2024-07-31 15:40 UTC, navidnasyry commented on Phase04/Phase4Solution/FullTextSearchTest/Controllers/search/StrategySet/AtLeastOneExistSetTest.cs
> +    public void GetValidDocs_ShouldReturnEmpty_WhereArgumentsAreInvalid(string[] wordsArray, string[] expectedDocs)
تست با اینپوت هایی با پیشوند های دیگر

2024-07-31 15:40 UTC, navidnasyry commented on Phase04/Phase4Solution/FullTextSearchTest/Controllers/search/StrategySet/AtLeastOneExistSetTest.cs
> +        Assert.NotEmpty(result);
دقیق تر لطفا

2024-07-31 15:40 UTC, navidnasyry commented on Phase04/Phase4Solution/FullTextSearchTest/Controllers/search/StrategySet/AtLeastOneExistSetTest.cs
> +        Assert.NotEmpty(result);
تست‌ها کلا دقیق تر باشه و حالت‌های مختلف تست شود

2024-07-31 15:40 UTC, navidnasyry commented on Phase04/Phase4Solution/FullTextSearchTest/Controllers/search/StrategySet/MustExistSetTest.cs
> +        // Act
مثل کامنت‌های کلاس قبل

2024-07-31 15:40 UTC, navidnasyry commented on Phase04/Phase4Solution/FullTextSearchTest/Controllers/search/StrategySet/MustNotExistSetTest.cs
> +    {
مثل قبل

2024-07-31 15:40 UTC, navidnasyry commented on Phase04/Phase4Solution/FullTextSearchTest/Controllers/search/WordSearcherTest.cs
> +        Assert.NotEmpty(result);
دقیق ترررر

2024-08-03 06:54 UTC, SwimmingRieux commented on Phase04/Phase4Solution/FullTextSearchTest/Controllers/Logic/DocumentsLoader/DocumentLoaderTest.cs
> +        Assert.Equal(result,check);
وقتی ترتیب ممکنه به هم بریزه از equivalent استفاده میکنیم.

2024-08-03 12:03 UTC, AliSK81 approved these changes
خسته نباشید

2024-08-03 12:03 UTC, AliSK81 commented on Phase04/Phase4Solution/FullTextSearch/Controllers/search/Abstraction/IAdvancedProcessor.cs
> +}
اینترفیس خالی خوب نیست

2024-08-03 12:03 UTC, AliSK81 commented on Phase04/Phase4Solution/FullTextSearch/Controllers/search/Abstraction/IBasicProcessor.cs
> +}
چرا خالیه

2024-08-03 12:03 UTC, AliSK81 commented on Phase04/Phase4Solution/FullTextSearch/Controllers/search/AdvancedQuerySearcher.cs
> +    }
چرا پیاده سازی نشده

2024-08-03 12:03 UTC, AliSK81 commented on Phase04/Phase4Solution/FullTextSearch/Controllers/search/AdvancedQuerySearcher.cs
> +    }
چیزی که در آینده قراره پیاده سازی بشه، الان کد نزنیم براش you ain't gonna need it

2024-08-03 12:03 UTC, AliSK81 commented on Phase04/Phase4Solution/FullTextSearch/Controllers/search/DocFinder.cs
> +        return result == null ? new List<string>() : result;
return result ?? [];

2024-08-03 12:03 UTC, AliSK81 commented on Phase04/Phase4Solution/FullTextSearch/Program.cs
> +        // var cacher = new InvertedIndexCatcher();
کد کامنت شده خوب نیست

2024-08-03 12:03 UTC, AliSK81 commented on Phase04/Phase4Solution/FullTextSearchTest/Controllers/search/AdvancedDocFinderTest.cs
چرا تست ها یه کانونشن یکسان ندارن
بعضی جاها قاعده نام تست should if هست بعضی جاها should when

2024-08-03 12:03 UTC, AliSK81 commented on Phase04/Phase4Solution/FullTextSearchTest/Controllers/search/WordSearcherTest.cs
> +    public void Search_ShouldThrowException_WhenQueryIsInvalid(string query)
WhenQueryIsNullOrEmpty

2024-08-03 12:03 UTC, AliSK81 commented on Phase04/Phase4Solution/FullTextSearchTest/Controllers/search/StrategySet/StrategySetFactoryTest.cs
> +        Assert.Equal(setName, name);
expected, actual
خوانایی تست ها هم مهمه

2024-08-03 12:44 UTC, navidnasyry approved these changes
سعی کنین از این به بعد از کتابخونه‌های [Fluent Assertions](https://www.fluentassertions.com/)و [NSubstitute](https://nsubstitute.github.io/)

2024-08-03 14:56 UTC, merged